NewCoffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('product.urls')),
    path('', include('user.urls')),
    path('', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('cart', CartController.as_view(), name='cart'),
    path('add-cart/', CartController.add_cart, name='addcart'),
    path('update-cart/', CartController.update_cart, name='update_cart'),
    path('remove-cart/', CartController.remove_cart, name='remove_cart'),
    path('empty-cart/', CartController.add_cart, name='empty_cart'),
    path('checkout/', CheckoutController.as_view(), name='checkout'),
    path('payment/', PaymentController.as_view(), name='payment'),
    path('pay/', PaymentController.post, name='pay'),

]

core/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', HomeController.as_view(), name='index'),
    path('about/', AboutController.as_view(), name='about'),
    path('contact/', ContactController.as_view(), name='contact'),
]

product/urls.py
from django.urls import path
from .views import ProductController


app_name = 'product'

urlpatterns = [
    path('cate/<str:cate_slug>/', ProductController.product, name='product'),
    path('product/<str:product_slug>/', ProductController.detail, name='detail'),
    path('cate/', ProductController.all, name='cate'),
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', LoginController.as_view(), name='login'),
    path('logout/', LogoutController.as_view(), name='logout'),
    path('register/', RegisterController.as_view(), name='register'),
    path('info/', InfoController.as_view(), name='info'),
    path('update_info/', InfoController.post, name='update_info'),
    path('log/', LoginController.post, name='log')
]

cart/models.py
from django.db import models
from product.models import Product


class Cart(models.Model):
    user = models.CharField(max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    total = models.IntegerField(default=0)

    def __str__(self):
        return self.user


class CartItem(models.Model):
    title = models.CharField(max_length=100)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.title

product/models.py
from django.db import models
from django.conf import settings
import django.utils.safestring as safestring
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(default='', max_length=100)
    slug = models.SlugField(default='', max_length=100, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)

        return super(Category, self).save(*args, **kwargs)


class Product(models.Model):
    title = models.CharField(default='', max_length=100)
    slug = models.SlugField(default='', max_length=100, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product')
    price = models.IntegerField(default=0)
    sale = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def image_tag(self):
        if self.image:
            return safestring.mark_safe('<img src="%s%s" width="150" height="150"/>' % (settings.MEDIA_URL, self.image))
        else:
            return ""

    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)

        return super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

cart/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.views import View
from product.models import Category
from cart.models import *
from order.models import Order

cart = {}


class CartController(View):
    def get(self, request):
        category = Category.objects.filter(active=1)
        quantity = 0
        try:
            cart = request.session['cart']

            for key, value in cart.items():
                quantity += int(value['quantity'])

            total = 0
            if len(cart) > 0:
                for key, value in cart.items():
                    if int(value['sale']) > 0:
                        total += int(value['sale']) * int(value['quantity'])
                    else:
                        total += int(value['price']) * int(value['quantity'])
                return render(request, 'cart.html', {
                    'category': category,
                    'cart_quantity': quantity,
                    'total': total,
                })
            else:
                return render(request, 'empty_cart.html', {
                    'category': category,
                    'cart_quantity': quantity
                })
        except:
            return render(request, 'empty_cart.html', {
                'category': category,
                'cart_quantity': quantity
            })

    def add_cart(request):
        if request.is_ajax():
            id = request.POST['id']
            num = request.POST['quantity']
            product = Product.objects.get(id=id)
            if id in cart.keys():
                item = {
                    'name': product.title,
                    'price': product.price,
                    'sale': product.sale,
                    'quantity': int(cart[id]['quantity']) + int(num)
                }
            else:
                item = {
                    'name': product.title,
                    'price': product.price,
                    'sale': product.sale,
                    'quantity': num
                }

        cart[id] = item

        request.session['cart'] = cart

        return render(request, 'cart.html')

    def update_cart(request):
        if request.is_ajax():
            id = request.POST['id']
            num = request.POST['quantity']
            product = Product.objects.get(id=id)
            if id in cart.keys():
                item = {
                    'name': product.title,
                    'price': product.price,
                    'sale': product.sale,
                    'quantity': num
                }

        cart[id] = item
        request.session['cart'] = cart

        return render(request, 'cart.html')

    def remove_cart(request):
        if request.is_ajax():
            id = request.POST['id']
            if id in cart.keys():
                del cart[id]

        request.session['cart'] = cart

        return render(request, 'cart.html')


class CheckoutController(View):
    def get(self, request):
        category = Category.objects.filter(active=1)
        return render(request, 'checkout.html', {
            'category': category
        })


class PaymentController(View):
    def get(self, request):
        category = Category.objects.filter(active=1)

        quantity = 0
        total = 0
        for key, value in cart.items():
            quantity += int(value['quantity'])
            if int(value['sale']) > 0:
                total += int(value['sale']) * int(value['quantity'])
            else:
                total += int(value['price']) * int(value['quantity'])

        return render(request, 'payment.html', {
            'category': category,
            'cart_quantity': quantity,
            'total': total
        })

    def post(request):
        name = request.POST['Name']
        address = request.POST['Address']
        email = request.POST['Email']
        note = request.POST['Note']

        lst = []

        c = Cart()
        total = 0
        for key, value in cart.items():
            if int(value['sale']) > 0:
                total += int(value['sale']) * int(value['quantity'])
            else:
                total += int(value['price']) * int(value['quantity'])
            lst.append(value['name'] + ' - ' + str(value['quantity']))

        c.user = name
        c.total = total
        c.save()

        i = Cart.objects.last()
        for key, value in cart.items():
            item = CartItem()
            item.title = i.user
            item.product_id = int(key)
            item.quantity = value['quantity']
            if int(value['sale']) > 0:

                item.price = int(value['sale'])
            else:
                item.price = int(value['price'])
            item.save()

        order = Order()
        order.user = i.user
        order.product = lst
        order.ship_address = address
        order.description = note
        order.save()


        message = 'Xin chào {0}, đơn hàng của bạn đã được đặt thành công.\nCác món bạn đã đặt là {1}.\nTổng giá trị đơn hàng là {2} vnđ (chưa bao gồm phí vận chuyển).\nĐịa chỉ giao hàng: {3}.\nCảm ơn quí khách đã sử dụng dịch vụ.'.format(name, lst, total, address)

        send_mail(
            'New Coffee',
            message,
            'newcoffee138hadac@gmail.com',
            [email]
        )

        cart.clear()
        request.session['cart'] = cart

        return redirect('home:index')

product/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from product.models import Category, Product
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger


class ProductController(View):
    def product(request, cate_slug):
        category = Category.objects.filter(active=1)

        quantity = 0
        try:
            cart = request.session['cart']
            for key, value in cart.items():
                quantity += int(value['quantity'])
        except:
            pass

        cate = get_object_or_404(Category, slug=cate_slug)
        product = cate.product_set.all()
        return render(request, 'product.html', {
            'category': category,
            'cart_quantity': quantity,
            'cate': cate,
            'product': product
        })

    def detail(request, product_slug):
        category = Category.objects.filter(active=1)
        detail = get_object_or_404(Product, slug=product_slug)
        cate = Category.objects.get(id=detail.category_id)

        quantity = 0
        try:
            cart = request.session['cart']
            for key, value in cart.items():
                quantity += int(value['quantity'])
        except:
            pass

        product = Product.objects.all()

        return render(request, 'detail.html', {
            'detail': detail,
            'category': category,
            'cart_quantity': quantity,
            'product': product,
            'cate': cate
        })

    def all(request):
        category = Category.objects.filter(active=1)

        product_list = Product.objects.all()
        paginator = Paginator(product_list, 12)
        page = request.GET.get('page', 1)
        try:
            product = paginator.page(page)
        except PageNotAnInteger:
            product = paginator.page(1)
        except EmptyPage:
            product = paginator.page(paginator.num_pages)

        return render(request, 'all.html', {
            'category': category,
            'product': product
        })

templates/all.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<!--================Categories Banner Area =================-->
<section class="categories_banner_area">
    <div class="container">
        <div class="c_banner_inner">
            <h3>New Coffee</h3>
            <ul>
                <li class="current"><a href="{% url 'home:index' %}">Trang chủ</a></li>
                <li class="current"><a href="#">All</a></li>
            </ul>
        </div>
    </div>
</section>
<!--================End Categories Banner Area =================-->

<!--================Categories Product Area =================-->
<section class="no_sidebar_2column_area">
    <div class="container">
        <div class="two_column_product">
            <div class="row">
                {% for product in product %}
                    {% if product.active == 1 %}
                        <div class="col-lg-3 col-sm-6">
                            <div class="l_product_item">
                                <div class="l_p_img">
                                    <a href="{% url 'product:detail' product.slug %}">
                                        <img class="img-fluid" src="/media/{{product.image}}" alt="" style="width:270px; height:360px">
                                    </a>
                                    {% if product.sale > 0 %}
                                        <h5 class="sale">Sale off 10%</h5>
                                    {% endif %}
                                </div>
                                <div class="l_p_text">
                                   <ul>
                                        <li class="p_icon"><a href="#"><i class="icon_piechart"></i></a></li>
                                        <li><a class="add_cart_btn" href="#" onclick="addCart({{ product.id }})">Mua</a></li>
                                        <li class="p_icon"><a href="#"><i class="icon_heart_alt"></i></a></li>
                                    </ul>
                                    <h4 id="product_name"> {{ product.title }} </h4>
                                    {% if product.sale > 0 %}
                                        <h5 id="product_price"><del> {{ product.price|intcomma }} VNĐ</del> {{ product.sale|intcomma }} VNĐ </h5>
                                    {% else %}
                                        <h5> {{ product.price|intcomma }} VNĐ </h5>
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <nav aria-label="Page navigation example" class="pagination_area">
                <ul class="pagination">
                    {% if product.has_previous %}
                        <li class="page-item next"><a class="page-link" href="?page={{product.previous_page_number}}"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
                    {% else %}
                        <li class="page-item next disable"><a class="page-link" href="#"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
                    {% endif %}

                    {% for i in product.paginator.page_range %}
                        {% if product.number == i %}
                            <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if product.has_next %}
                        <li class="page-item next"><a class="page-link" href="?page={{product.next_page_number}}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</section>
<!--================End Categories Product Area =================-->
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!--================Categories Banner Area =================-->
        <section class="categories_banner_area">
            <div class="container">
                <div class="c_banner_inner">
                    <h3>Giỏ hàng</h3>
                    <ul>
                        <li><a href="#">Trang chủ</a></li>
                        <li><a href="shopping-cart2.html">Thanh toán</a></li>
                    </ul>
                </div>
            </div>
        </section>
        <!--================End Categories Banner Area =================-->

        <!--================End Categories Banner Area =================-->
        <section class="checkout_method_area p_100">
            <div class="container">
                <div class="row">
                    <div class="checkout_main_area">
                        <div class="checkout_prosses">
                            <div class="row m0">
                                <div class="col-md-6">
                                    <div class="checkout_method">
                                        <h3>Chọn là khách hoặc đăng ký thành viên</h3>
                                        <h4>Đăng ký thành viên để nhận ưu đãi hoặc bấm tiếp tục để thanh toán như khách</h4>
                                         <form role="form" class="radio_area">
                                            <ul class="radio_style">
                                                <li>
                                                    <input type="radio" id="f-option" name="selector">
                                                    <label for="f-option">Khách</label>
                                                    <div class="check"></div>
                                                </li>
                                                <li>
                                                    <input type="radio" id="s-option" name="selector">
                                                    <label for="s-option">Thành viên</label>
                                                    <div class="check"><div class="inside"></div></div>
                                                </li>
                                            </ul>
                                          </form>
                                          <h5>register and save time !</h5>
                                          <h6>Register with us for future convenience:</h6>
                                          <a class="checkout_list" href="#"><i class="arrow_carrot-right"></i> Fast and easy check out</a>
                                          <a class="checkout_list" href="#"><i class="arrow_carrot-right"></i> Easy access to your order history and status</a>
                                          <a class="update_btn" href="{% url 'cart:payment' %}"><span>Tiếp tục</span></a>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="row checkout_from_area">
                                       <h2>Đã có tài khoản ?</h2>
                                       <p>Đăng nhập bên dưới</p>
                                        <form role="form">
                                            <div class="form-group">
                                                <label for="Name">Tên đăng nhập<span>*</span></label>
                                                <input type="text" class="form-control" id="Name">
                                            </div>
                                            <div class="form-group">
                                                <label for="pwd">Mật khẩu<span>*</span></label>
                                                <input type="password" class="form-control" id="pwd">
                                            </div>
                                            <h3>* Các trường này là bắt buộc</h3>
                                            <div class="forgot_area">
                                                <button type="submit" class="btn update_btn btn-default">Đăng nhập</button>
                                                <h4>Quên mật khẩu?</h4>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Categories Banner Area =================-->
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

templates/header.html
{% load static %}
<style>
.cart_quantity a:before {
  content: "{{ cart_quantity }}";
  height: 20px;
  width: 20px;
  border-radius: 50%;
  text-align: center;
  color: #fff;
  font-family: "Poppins", sans-serif;
  font-size: 12px;
  position: absolute;
  font-weight: normal;
  right: 10px;
  bottom: 13px;
  background: #d91522;
  line-height: 20px;
}




</style>

<header class="shop_header_area carousel_menu_area" style="border-bottom-style:solid; border-color:red">
    <div class="carousel_top_header black_top_header row m0">
        <div class="container">
            <div class="carousel_top_h_inner">
                <div class="float-md-left">
                    <div class="top_header_middle">
                        <a href="http://fb.com/NewCoffee138" target="blank" style="color:aqua; margin-right:10px"><i
                                class="fa fa-facebook"></i>New Coffee</a>
                        <a href="#" style="color:aqua; margin-right:10px"><i class="fa fa-phone"></i>076 229 6277</a>
                        <a href="#" style="color:aqua; margin-right:10px"><i class="fa fa-envelope"></i>nthoang31097@gmail.com</a>
                        <a href="#" style="color:aqua; margin-right:10px"><i class="fa fa-envelope"></i>{{ a }}</a>
                    </div>
                </div>
                {% if user.username %}
                <div class="float-md-right">
                    <ul class="account_list">
                        <li style="color:aqua">Chào, {{ user.username }}</li>
                        <li><a href="{% url 'user:logout' %}">Đăng xuất</a></li>
                        {% if user.is_staff %}
                        <li><a href="{% url 'admin:index' %}" target="_blank">Quản lý</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% else %}
                <div class="float-md-right">
                    <ul class="account_list">
                        <li>
                            <a href="{% url 'user:login' %}">Đăng nhập</a>
<!--                            <a href="{% url 'user:login' %}" data-toggle="modal" data-target="#loginForm">Đăng nhập</a>-->
                        </li>
                        <li>
                            <a href="{% url 'user:register' %}">Đăng ký</a>
<!--                            <a href="{% url 'user:register' %}" data-toggle="modal" data-target="#registerForm">Đăng ký</a>-->
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="carousel_menu_inner">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="height:77px; padding-bottom:14px">
                <a class="navbar-brand" href="/"><img src="{% static 'img/Logo.jpg' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>

                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:index' %}" style="color:red">Trang
                            chủ</a></li>
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Menu <i class="fa fa-angle-down" aria-hidden="true"></i>
                            </a>
                            <ul class="dropdown-menu">
                                {% for item in category %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'product:product' item.slug %}">{{ item.title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:about' %}">Giới thiệu</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:contact' %}">Liên hệ</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'cart:cart' %}">Giỏ hàng</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:info' %}">Tài khoản</a></li>
                    </ul>
                    <ul class="navbar-nav justify-content-end">
                        <li class="user_icon"><a href="{% url 'user:info' %}"><i class="icon-user icons"></i></a></li>
                        <li class="cart_quantity"><a href="{% url 'cart:cart' %}"><i class="icon-handbag icons"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <!--================ Login Form =================-->
<!--    <div class="modal fade" id="loginForm" tabindex="-1" role="dialog" aria-labelledby="login"-->
<!--         aria-hidden="true">-->
<!--        <div class="modal-dialog" role="document">-->
<!--            <div class="modal-content w3l-login-form">-->
<!--                <div class="modal-body ">-->
<!--                    <h1><span style="color:red">N</span>ew <span style="color:red">C</span>offee</h1>-->
<!--                    <form action="" method="POST">-->
<!--                        {% csrf_token %}-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Tên đăng nhập:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-user"></i>-->
<!--                                <input type="text" id="Username" class="form-control" placeholder="Nhập tên đăng nhập" required="required" name="Username"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Mật khẩu:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-unlock"></i>-->
<!--                                <input type="password" id="Password" class="form-control" placeholder="Nhập mật khẩu" required="required" name="Password"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="forgot">-->
<!--                            <a href="#">Quên mật khẩu?</a>-->
<!--                        </div>-->
<!--                        <button type="button" id="btnLogin" class="button">Đăng nhập</button>-->
<!--                    </form>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <!--================ End Login Form =================-->

    <!--================ Register Form =================-->
<!--    <div class="modal fade" id="registerForm" tabindex="-1" role="dialog" aria-labelledby="register"-->
<!--         aria-hidden="true">-->
<!--        <div class="modal-dialog" role="document">-->
<!--            <div class="modal-content w3l-login-form">-->
<!--                <div class="modal-body ">-->
<!--                    <h1><span style="color:red">N</span>ew <span style="color:red">C</span>offee</h1>-->
<!--                    <form action="" method="POST">-->
<!--                        {% csrf_token %}-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Tên đăng nhập:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-user"></i>-->
<!--                                <input type="text" class="form-control" placeholder="Tên đăng nhập" required="required"-->
<!--                                       name="Username"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Email:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-envelope"></i>-->
<!--                                <input type="text" class="form-control" placeholder="Nhập email" required=""-->
<!--                                       name="Email"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Số điện thoại:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-phone"></i>-->
<!--                                <input type="text" class="form-control" placeholder="Nhập số điện thoại" name="Phone"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Địa chỉ:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-map"></i>-->
<!--                                <input type="text" class="form-control" placeholder="Nhập địa chỉ" name="Address"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Mật khẩu:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-unlock"></i>-->
<!--                                <input type="password" id="password1" class="form-control" placeholder="Nhập mật khẩu"-->
<!--                                       required="required" name="Password"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class=" w3l-form-group">-->
<!--                            <label>Nhập lại mật khẩu:</label>-->
<!--                            <div class="group">-->
<!--                                <i class="fa fa-unlock"></i>-->
<!--                                <input type="password" id="password2" class="form-control"-->
<!--                                       placeholder="Nhập lại mật khẩu" required="required" name="Confirm_Password"/>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <button class="button" type="submit">Đăng ký</button>-->
<!--                    </form>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <!--================ End Register Form =================-->
</header>